export default {
  catagory: [
    {
      id: '1',
      catagoryName: 'chiness foods',
      images: require('./pics/chinessFoods.png'),
    },
    {
      id: '2',
      catagoryName: 'sea foods',
      images: require('./pics/seaFoods.png'),
    },
    {
      id: '3',
      catagoryName: 'salads',
      images: require('./pics/salads.png'),
    },
    {
      id: '4',
      catagoryName: 'desserts',
      images: require('./pics/desserts.png'),
    },
    {
      id: '5',
      catagoryName: 'drinks',
      images: require('./pics/drinks.png'),
    },
  ],
  subCatagory: [
    {
      id: '1',
      catagoryId: '1',
      subCatagoryName: 'dim sum',
      images: require('./pics/dimSum.png'),
      price: '8',
    },
    {
      id: '2',
      catagoryId: '1',
      subCatagoryName: 'quick noodles',
      images: require('./pics/quickNoodles.png'),
      price: '5',
    },
    {
      id: '3',
      catagoryId: '1',
      subCatagoryName: 'spring rolls',
      images: require('./pics/springRolls.png'),
      price: '10',
    },
    {
      id: '4',
      catagoryId: '1',
      subCatagoryName: 'cantonese chicken soup',
      images: require('./pics/cantoneseChickenSoup.png'),
      price: '6',
    },
    {
      id: '5',
      catagoryId: '1',
      subCatagoryName: 'peri-peri chicken satay',
      images: require('./pics/peri-peri chicken satay.png'),
      price: '4',
    },
    {
      id: '6',
      catagoryId: '2',
      subCatagoryName: 'crab seafood',
      images: require('./pics/crab seafood.png'),
      price: '6',
    },
    {
      id: '7',
      catagoryId: '2',
      subCatagoryName: 'shrimp seafood',
      images: require('./pics/shrimpSeafood.png'),
      price: '7',
    },
    {
      id: '8',
      catagoryId: '2',
      subCatagoryName: 'crayfish seafood',
      images: require('./pics/crayfishSeafood.png'),
      price: '4',
    },
    {
      id: '9',
      catagoryId: '2',
      subCatagoryName: 'finger fish seafood',
      images: require('./pics/fingerFish.png'),
      price: '8',
    },
    {
      id: '10',
      catagoryId: '2',
      subCatagoryName: 'yellowfin tuna seafood',
      images: require('./pics/yellowfin tuna seafood.png'),
      price: '12',
    },
    {
      id: '11',
      catagoryId: '3',
      subCatagoryName: 'vegetable salad',
      images: require('./pics/vegetableSalad.png'),
      price: '8',
    },
    {
      id: '12',
      catagoryId: '3',
      subCatagoryName: 'fruit salad',
      images: require('./pics/fruitSalad.png'),
      price: '7',
    },
    {
      id: '13',
      catagoryId: '3',
      subCatagoryName: 'cream fruit salad',
      images: require('./pics/creamFruitSalad.png'),
      price: '9',
    },
    {
      id: '14',
      catagoryId: '3',
      subCatagoryName: 'filipino fruit salad',
      images: require('./pics/filipinoFruitSalad.png'),
      price: '5',
    },
    {
      id: '15',
      catagoryId: '3',
      subCatagoryName: 'buko salad',
      images: require('./pics/bukoSalad.png'),
      price: '9',
    },
    {
      id: '16',
      catagoryId: '4',
      subCatagoryName: 'decadent dessert',
      images: require('./pics/decadentDessert.png'),
      price: '10',
    },
    {
      id: '17',
      catagoryId: '4',
      subCatagoryName: 'cakes',
      images: require('./pics/cakes.png'),
      price: '10',
    },
    {
      id: '18',
      catagoryId: '4',
      subCatagoryName: 'casada',
      images: require('./pics/casada.png'),
      price: '9',
    },
    {
      id: '19',
      catagoryId: '4',
      subCatagoryName: 'ice cream',
      images: require('./pics/iceCream.png'),
      price: '8',
    },
    {
      id: '20',
      catagoryId: '4',
      subCatagoryName: 'minni pumps',
      images: require('./pics/minniPumps.png'),
      price: '5',
    },
    {
      id: '21',
      catagoryId: '5',
      subCatagoryName: 'milk shake',
      images: require('./pics/milkShake.png'),
      price: '5',
    },
    {
      id: '22',
      catagoryId: '5',
      subCatagoryName: 'coffee',
      images: require('./pics/coffee.png'),
      price: '5',
    },
    {
      id: '23',
      catagoryId: '5',
      subCatagoryName: 'soft drink',
      images: require('./pics/softDrink.png'),
      price: '5',
    },
    {
      id: '24',
      catagoryId: '5',
      subCatagoryName: 'fresh juices',
      images: require('./pics/freshJuices.png'),
      price: '5',
    },
  ],
  product: [
    {
      id: '1',
      subCatgoryId: '1',
      productName: 'dim sum',
      images: require('./pics/dimSum.png'),
      price: '8',
      discription:
        'Dim sum is a large range of small dishes that Cantonese people traditionally enjoy in restaurants for breakfast and lunch.',
    },
    {
      id: '2',
      subCatgoryId: '1',
      productName: 'quick noodles',
      images: require('./pics/quickNoodles.png'),
      price: '5',
      discription:
        'Quick Noodle Recipes. These quick noodle recipes can be prepared and served in just 20 minutes or less, so are perfect for anyone looking to prepare a tasty mid-week meal in a hurry.',
    },
    {
      id: '3',
      subCatgoryId: '1',
      productName: 'spring rolls',
      images: require('./pics/springRolls.png'),
      price: '10',
      discription:
        'Directions Step 1 Bring a medium saucepan of water to boil. Boil rice vermicelli 3 to 5 minutes, or until al dente, and drain.',
    },
    {
      id: '4',
      subCatgoryId: '1',
      productName: 'cantonese chicken soup',
      images: require('./pics/cantoneseChickenSoup.png'),
      price: '6',
      discription:
        'In Canton, Wonton Soup can be a full meal in itself, consisting of thin egg noodles and several pork and prawn wontons in a pork or chicken soup broth or noodle broth.',
    },
    {
      id: '5',
      subCatgoryId: '1',
      productName: 'peri-peri chicken satay',
      images: require('./pics/peri-peri chicken satay.png'),
      price: '4',
      discription:
        'A satay variant from Ambal, Kebumen, Central Java. This satay uses a native breed of poultry, ayam kampung. The sauce is not based on peanuts.',
    },
    {
      id: '6',
      subCatgoryId: '2',
      productName: 'crab seafood',
      images: require('./pics/crab seafood.png'),
      price: '6',
      discription:
        'the free encyclopedia Crab sticks, krab sticks, imitation crab meat or seafood sticks are a type of seafood made of starch and finely pulverized white fish.',
    },
    {
      id: '7',
      subCatgoryId: '2',
      productName: 'shrimp seafood',
      images: require('./pics/shrimpSeafood.png'),
      price: '7',
      discription:
        'a small free-swimming crustacean with an elongated body, typically marine and frequently of commercial importance as food.',
    },
    {
      id: '8',
      subCatgoryId: '2',
      productName: 'crayfish seafood',
      images: require('./pics/crayfishSeafood.png'),
      price: '4',
      discription:
        'Crayfish are freshwater crustaceans resembling small lobsters (to which they are related). In some parts of the United States.',
    },
    {
      id: '9',
      subCatgoryId: '2',
      productName: 'finger fish seafood',
      images: require('./pics/fingerFish.png'),
      price: '8',
      discription:
        'the free encyclopedia A fish finger sandwich is a sandwich containing fish fingers, a battered or breaded fish product.',
    },
    {
      id: '10',
      subCatgoryId: '2',
      productName: 'yellowfin tuna seafood',
      images: require('./pics/yellowfin tuna seafood.png'),
      price: '12',
      discription:
        'The yellowfin tuna is a species of tuna found in pelagic waters of tropical and subtropical oceans worldwide. Yellowfin is often marketed as ahi.',
    },
    {
      id: '11',
      subCatgoryId: '3',
      productName: 'vegetable salad',
      images: require('./pics/vegetableSalad.png'),
      price: '8',
      discription:
        'Vegetable salad Made from yardlong beans, carrots and cabbage which are pickled in vinegar and dried chili peppers.',
    },
    {
      id: '12',
      subCatgoryId: '3',
      productName: 'fruit salad',
      images: require('./pics/fruitSalad.png'),
      price: '7',
      discription:
        'Fruit salad is a dish consisting of various kinds of fruit, sometimes served in a liquid, either their own juices or a syrup. In different forms.',
    },
    {
      id: '13',
      subCatgoryId: '3',
      productName: 'cream fruit salad',
      images: require('./pics/creamFruitSalad.png'),
      price: '9',
      discription:
        'Fruit salad is a dish consisting of various kinds of fruit, sometimes served in a liquid, either their own juices or a syrup.',
    },
    {
      id: '14',
      subCatgoryId: '3',
      productName: 'filipino fruit salad',
      images: require('./pics/filipinoFruitSalad.png'),
      price: '5',
      discription:
        'A fruit salad is–from the name itself–a combination of a variety of fruits that is usually served partnered with a syrup. It can be served as a snack.',
    },
    {
      id: '15',
      subCatgoryId: '3',
      productName: 'buko salad',
      images: require('./pics/bukoSalad.png'),
      price: '9',
      discription:
        'the free encyclopedia Buko salad, usually anglicized as young coconut salad.',
    },
    {
      id: '16',
      subCatgoryId: '4',
      productName: 'decadent dessert',
      images: require('./pics/decadentDessert.png'),
      price: '10',
      discription:
        'Dessert is a course that concludes a meal. The course usually consists of sweet foods, such as confections.',
    },
    {
      id: '17',
      subCatgoryId: '4',
      productName: 'cakes',
      images: require('./pics/cakes.png'),
      price: '10',
      discription:
        'Cake is a form of sweet food made from flour, sugar, and other ingredients, that is usually baked. In their oldest forms, cakes were modifications of bread,',
    },
    {
      id: '18',
      subCatgoryId: '4',
      productName: 'casada',
      images: require('./pics/casada.png'),
      price: '9',
      discription:
        'Cassata or cassata siciliana is a traditional sweet from Sicily, Italy. Cassata consists of round sponge cake moistened with fruit juices or liqueur and layered with ricotta cheese and candied fruit.',
    },
    {
      id: '19',
      subCatgoryId: '4',
      productName: 'ice cream',
      images: require('./pics/iceCream.png'),
      price: '8',
      discription:
        'Ice cream (derived from earlier iced cream or cream ice) is a sweetened frozen food typically eaten as a snack or dessert. It may be made from dairy milk or cream and is flavoured with a sweetener,',
    },
    {
      id: '20',
      subCatgoryId: '4',
      productName: 'minni pumps',
      images: require('./pics/minniPumps.png'),
      price: '5',
      discription:
        'Dessert is a course that concludes a meal. The course usually consists of sweet foods, such as confections, and possibly a beverage such as dessert wine or liqueur.',
    },
    {
      id: '21',
      subCatgoryId: '5',
      productName: 'milk shake',
      images: require('./pics/milkShake.png'),
      price: '5',
      discription:
        "A milkshake, or simply shake, is a drink that is traditionally made by blending cow's milk, ice cream, and flavorings or sweeteners such as butterscotch.",
    },
    {
      id: '22',
      subCatgoryId: '5',
      productName: 'coffee',
      images: require('./pics/coffee.png'),
      price: '5',
      discription:
        "If you love coffee, be sure to browse Walmart's extensive selection of coffee products, where you'll find lots of ways to enjoy the perfect cup of joe.",
    },
    {
      id: '23',
      subCatgoryId: '5',
      productName: 'soft drink',
      images: require('./pics/softDrink.png'),
      price: '5',
      discription:
        'A soft drink (see § Terminology for other names) is a drink that usually contains carbonated water (although some vitamin waters and lemonades are not carbonated).',
    },
    {
      id: '24',
      subCatgoryId: '5',
      productName: 'fresh juices',
      images: require('./pics/freshJuices.png'),
      price: '5',
      discription:
        'Juicing extracts the juice from fresh fruits or vegetables. The liquid contains most of the vitamins, minerals and plant chemicals (phytonutrients) found in the fruit.',
    },
  ],
};
